@startuml
interface Component {
    +operation(): void
}

class Leaf implements Component {
    +operation(): void
}

class Composite implements Component {
    -children: Component[]
    +operation(): void
    +add(component: Component): void
    +remove(component: Component): void
    +getChild(index: int): Component
}

Component <|-- Leaf
Component <|-- Composite
Composite --> Component : contains
@enduml